#################################################
# EKSCTL Config for EKS Set Up

#################################################

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-cluster
  region: ap-southeast-1
  version: "1.13"

#vpc:
#  securityGroup: "sg-0f2ae54eb340e8191"
#  sharedNodeSecurityGroup: "sg-02a47cee779b317a7"
#  subnets:
#    Private:
#      eu-north-1c:
#          id: "subnet-065fe8f12d0910d06"
#          cidr: "10.1.128.0/19"
#      eu-north-1b:
#          id: "subnet-06ebc3649c1321fc5"
#          cidr: "10.1.96.0/19"

iam:
  serviceRoleARN: "arn:aws:iam::991071810573:role/eks-cluster-service-role"

nodeGroups:
  - name: eks-ng1
    desiredCapacity: 3
#    instanceType: m5.large
#    privateNetworking: true
#    securityGroups:
#      withShared: true
#      withLocal: false
#      attachIDs: [sg-0b85ff315ea644478]
    iam:
      instanceProfileARN: "arn:aws:iam::991071810573:instance-profile/eks-node-service"
      instanceRoleARN: "arn:aws:iam::991071810573:role/eks-node-service"